<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $countries=[
['country_name' => 'Afghanistan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Aland Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Albania','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Algeria','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'American Samoa','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Andorra','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Angola','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Anguilla','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Antigua and Barbuda','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Argentina','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Armenia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Aruba','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Australia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Austria','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Azerbaijan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bahamas','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bahrain','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bangladesh','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Barbados','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Belarus','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Belgium','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Belize','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Benin','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bermuda','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bhutan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bolivia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => '"Bonaire, Saint Eustatius and Saba"','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bosnia and Herzegovina','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Botswana','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Brazil','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'British Virgin Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Brunei','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Bulgaria','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Burkina Faso','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Burundi','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cambodia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cameroon','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Canada','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cape Verde','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cayman Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Central African Republic','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Chad','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Chile','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'China','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Christmas Island','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cocos Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Colombia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Comoros','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cook Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Costa Rica','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Croatia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cuba','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Curacao','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Cyprus','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Czech Republic','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Democratic Republic of the Congo','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Denmark','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Djibouti','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Dominica','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Dominican Republic','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'East Timor','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Ecuador','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Egypt','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'El Salvador','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Equatorial Guinea','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Eritrea','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Estonia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Ethiopia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Falkland Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Faroe Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Fiji','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Finland','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'France','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'French Guiana','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'French Polynesia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'French Southern Territories','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Gabon','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Gambia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Georgia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Germany','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Ghana','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Gibraltar','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Greece','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Greenland','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Grenada','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Guadeloupe','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Guam','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Guatemala','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Guernsey','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Guinea','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Guinea-Bissau','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Guyana','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Haiti','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Honduras','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Hong Kong','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Hungary','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Iceland','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'India','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Indonesia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Iran','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Iraq','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Ireland','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Isle of Man','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Israel','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Italy','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Ivory Coast','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Jamaica','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Japan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Jersey','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Jordan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Kazakhstan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Kenya','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Kiribati','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Kosovo','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Kuwait','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Kyrgyzstan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Laos','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Latvia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Lebanon','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Lesotho','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Liberia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Libya','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Liechtenstein','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Lithuania','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Luxembourg','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Macao','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Macedonia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Madagascar','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Malawi','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Malaysia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Maldives','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Mali','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Malta','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Marshall Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Martinique','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Mauritania','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Mauritius','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Mayotte','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Mexico','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Micronesia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Moldova','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Monaco','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Mongolia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Montenegro','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Montserrat','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Morocco','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Mozambique','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Myanmar','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Namibia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Nauru','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Nepal','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Netherlands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'New Caledonia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'New Zealand','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Nicaragua','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Niger','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Nigeria','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Niue','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Norfolk Island','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'North Korea','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Northern Mariana Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Norway','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Oman','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Pakistan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Palau','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Palestinian Territory','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Panama','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Papua New Guinea','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Paraguay','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Peru','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Philippines','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Pitcairn','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Poland','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Portugal','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Puerto Rico','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Qatar','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Republic of the Congo','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Reunion','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Romania','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Russia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Rwanda','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saint Barthelemy','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saint Helena','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saint Kitts and Nevis','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saint Lucia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saint Martin','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saint Pierre and Miquelon','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saint Vincent and the Grenadines','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Samoa','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'San Marino','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Sao Tome and Principe','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Saudi Arabia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Senegal','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Serbia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Seychelles','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Sierra Leone','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Singapore','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Sint Maarten','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Slovakia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Slovenia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Solomon Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Somalia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'South Africa','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'South Georgia and the South Sandwich Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'South Korea','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'South Sudan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Spain','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Sri Lanka','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Sudan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Suriname','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Svalbard and Jan Mayen','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Swaziland','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Sweden','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Switzerland','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Syria','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Taiwan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Tajikistan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Tanzania','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Thailand','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Togo','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Tonga','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Trinidad and Tobago','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Tunisia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Turkey','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Turkmenistan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Turks and Caicos Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Tuvalu','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'U.S. Virgin Islands','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Uganda','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Ukraine','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'United Arab Emirates','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'United Kingdom','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'United States','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Uruguay','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Uzbekistan','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Vanuatu','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Vatican','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Venezuela','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Vietnam','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Wallis and Futuna','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Western Sahara','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Yemen','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Zambia','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
['country_name' => 'Zimbabwe','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
        ];
        
    	foreach ($countries as $country) {
    		$c = new Country;
    		$c->name = $country['country_name'];
    		$c->save();
    	}
    }
}
